// Fabric taxonomy + climate-relevant property scores.
//
// Each fabric is rated on 5-point scales for the properties that matter most
// in the use cases Chromatique cares about:
//   - breathability: air-flow through the fabric (5 = max breath)
//   - wicking: pulls sweat away from skin (5 = pulls and dries fastest)
//   - drape: how the fabric falls (1 = stiff, 5 = liquid)
//   - wrinkle: how much it creases with wear (1 = never, 5 = lots)
//   - durability: how it holds up to repeated washing/wear (5 = years)
//
// "tropicalFit" is a composite score (1-5) for how well the fabric performs
// in hot + humid conditions. Used by the rules engine to rank recommendations.
//
// Sources synthesized from: textile-industry property charts, OEKO-TEX
// documentation, the textile-science chapter of "Textiles" (Kadolph, 11th ed.),
// and ADD_RESEARCH §4.2 (Singapore/SEA climate context).

export type FabricCategory =
  | "natural-plant"   // linen, cotton, hemp, ramie
  | "natural-animal"  // silk, wool, cashmere
  | "regenerated"     // Tencel, modal, viscose, bamboo
  | "synthetic"       // polyester, nylon, acrylic
  | "blend"           // mixed
  | "specialty";      // seersucker, eyelet, gauze

export type Tone = "warm" | "cool" | "neutral";

export interface Fabric {
  slug: string;
  name: string;
  alternativeNames?: string[];
  category: FabricCategory;
  source: string;                // what it's made from, plain English
  texture: string;               // one-line texture description
  /** 1 = poor for tropical, 5 = ideal */
  tropicalFit: number;
  /** 1-5 scales */
  breathability: number;
  wicking: number;
  drape: number;
  wrinkle: number;
  durability: number;
  /** Common occasions this fabric shines in */
  occasions: ("Office" | "Weekend" | "Going out" | "Outdoor" | "Travel")[];
  /** Quick-feel "tone" for matching season palettes */
  warmthAffinity: Tone[];        // which seasons this is naturally well-suited to
  /** Higher = more sustainable / responsible. 1-5 */
  sustainability: number;
  /** Skin-friendliness for normal-sensitive skin (chemical residues, weave smoothness). 1-5 */
  skinFriendly: number;
  /** Safety for sensitive / reactive skin. 1-5.
   *  5 = ultra-smooth, no chemical finishes, dermatologist-recommended (silk, OEKO-TEX certified TENCEL, organic cotton).
   *  1 = guaranteed flare trigger (wool, polyester fleece, acrylic, formaldehyde-treated easy-care cottons).
   *  Internally still labelled "eczemaFriendly" so the column also serves anyone with eczema, contact dermatitis, or chronic flares. */
  eczemaFriendly: number;
  /** Suitability for dry skin (lacks oil/moisture, prone to itch). 1-5.
   *  5 = retains skin moisture, smooth-on-skin (silk, modal, TENCEL, cotton-modal, brushed cottons).
   *  1 = strips skin oils or causes friction itch (performance synthetics, acrylic, ramie). */
  dryFriendly: number;
  /** Thermal performance by body type. 1-5 each.
   *  hotRunner: how comfortable a person who runs hot will be (favours airflow + wicking)
   *  coldRunner: how comfortable a person who runs cold will be in air-con / layering contexts
   *  Some fabrics (linen, TENCEL, merino) are thermo-regulating and score well on both. */
  thermalFit: { hotRunner: number; coldRunner: number };
  /** Care notes one-liner */
  care: string;
  /** Label keywords to look for when shopping */
  labelKeywords: string[];
  /** One-sentence "why this fabric matters" */
  why: string;
  /** Optional: explicit red-flag note (e.g. 100% acrylic, polyester fleece) per FABRIC_RESEARCH §2c */
  redFlag?: string;
}

export const FABRICS: Fabric[] = [
  // ─── NATURAL PLANT (best for tropics) ─────────────────────────────────
  {
    slug: "linen",
    name: "Linen",
    alternativeNames: ["Flax"],
    category: "natural-plant",
    source: "Flax stalk fibres",
    texture: "Crisp, textured, naturally cool to the touch",
    tropicalFit: 5,
    breathability: 5,
    wicking: 5,
    drape: 3,
    wrinkle: 5,
    durability: 4,
    occasions: ["Office", "Weekend", "Going out", "Travel"],
    warmthAffinity: ["warm", "neutral", "cool"],
    sustainability: 5,
    skinFriendly: 5,
    eczemaFriendly: 4,
    dryFriendly: 3,
    thermalFit: { hotRunner: 5, coldRunner: 2 },
    care: "Machine wash cold, air-dry, iron when slightly damp. Wrinkles are the look.",
    labelKeywords: ["100% Linen", "Pure Linen", "Linen blend"],
    why: "The fastest-wicking natural fibre. Wrinkles freely but that's the texture you're buying.",
  },
  {
    slug: "lightweight-cotton",
    name: "Lightweight Cotton",
    alternativeNames: ["Voile", "Batiste", "Cotton Lawn"],
    category: "natural-plant",
    source: "Cotton plant fibres, finely woven",
    texture: "Smooth, soft, airy with a slight crispness",
    tropicalFit: 4,
    breathability: 4,
    wicking: 3,
    drape: 4,
    wrinkle: 3,
    durability: 4,
    occasions: ["Office", "Weekend", "Going out"],
    warmthAffinity: ["warm", "cool", "neutral"],
    sustainability: 3,
    skinFriendly: 5,
    eczemaFriendly: 4,
    dryFriendly: 4,
    thermalFit: { hotRunner: 4, coldRunner: 3 },
    care: "Standard cotton care. Avoid hot dryer to preserve fibres.",
    labelKeywords: ["100% Cotton", "Cotton voile", "Cotton lawn"],
    why: "Workhorse for daily wear, breathable but not as wicking as linen.",
  },
  {
    slug: "organic-cotton",
    name: "Organic Cotton",
    category: "natural-plant",
    source: "Cotton grown without synthetic pesticides",
    texture: "Same as cotton but free of chemical residues",
    tropicalFit: 4,
    breathability: 4,
    wicking: 3,
    drape: 3,
    wrinkle: 3,
    durability: 4,
    occasions: ["Office", "Weekend", "Travel"],
    warmthAffinity: ["warm", "cool", "neutral"],
    sustainability: 5,
    skinFriendly: 5,
    eczemaFriendly: 5,
    dryFriendly: 5,
    thermalFit: { hotRunner: 4, coldRunner: 3 },
    care: "Same as cotton. Mild detergent preserves the no-residue benefit.",
    labelKeywords: ["GOTS Certified", "Organic Cotton", "OEKO-TEX Standard 100"],
    why: "Dermatologist-recommended for eczema. No formaldehyde easy-care finishes, no pesticide residues.",
  },
  {
    slug: "hemp",
    name: "Hemp",
    category: "natural-plant",
    source: "Cannabis sativa plant stalks",
    texture: "Slightly coarse initially, softens dramatically with washing",
    tropicalFit: 5,
    breathability: 5,
    wicking: 5,
    drape: 2,
    wrinkle: 4,
    durability: 5,
    occasions: ["Outdoor", "Weekend", "Travel"],
    warmthAffinity: ["warm", "neutral"],
    sustainability: 5,
    skinFriendly: 4,
    eczemaFriendly: 4,
    dryFriendly: 3,
    thermalFit: { hotRunner: 5, coldRunner: 3 },
    care: "Machine wash, air-dry. Gets softer with every wash.",
    labelKeywords: ["100% Hemp", "Hemp blend"],
    why: "More durable than cotton, more breathable than linen, naturally antimicrobial. UPF 50+ sun protection.",
  },
  {
    slug: "ramie",
    name: "Ramie",
    category: "natural-plant",
    source: "Asian flowering plant fibre",
    texture: "Crisp like linen but with a subtle sheen",
    tropicalFit: 5,
    breathability: 5,
    wicking: 5,
    drape: 2,
    wrinkle: 4,
    durability: 4,
    occasions: ["Office", "Weekend"],
    warmthAffinity: ["warm", "neutral"],
    sustainability: 4,
    skinFriendly: 4,
    eczemaFriendly: 3,
    dryFriendly: 2,
    thermalFit: { hotRunner: 5, coldRunner: 2 },
    care: "Dry-clean for structured pieces, hand-wash casual.",
    labelKeywords: ["Ramie", "Ramie blend"],
    why: "Asian alternative to linen with a hint of luxury sheen. Crisper hand than linen.",
  },

  // ─── REGENERATED CELLULOSIC (excellent for tropics) ───────────────────
  {
    slug: "tencel-lyocell",
    name: "Tencel",
    alternativeNames: ["Lyocell"],
    category: "regenerated",
    source: "Sustainably sourced eucalyptus pulp",
    texture: "Silky, smooth, slightly cool",
    tropicalFit: 5,
    breathability: 4,
    wicking: 5,
    drape: 5,
    wrinkle: 2,
    durability: 4,
    occasions: ["Office", "Going out", "Travel"],
    warmthAffinity: ["warm", "cool", "neutral"],
    sustainability: 5,
    skinFriendly: 5,
    eczemaFriendly: 5,
    dryFriendly: 5,
    thermalFit: { hotRunner: 5, coldRunner: 4 },
    care: "Gentle wash, hang to dry. Resists wrinkles.",
    labelKeywords: ["Tencel", "Lyocell", "TENCEL Lyocell"],
    why: "Drape of silk, breathability of cotton, naturally anti-bacterial. Closed-loop solvent process (95%+ recovery).",
  },
  {
    slug: "modal",
    name: "Modal",
    category: "regenerated",
    source: "Beech tree pulp",
    texture: "Buttery soft, fluid drape",
    tropicalFit: 4,
    breathability: 4,
    wicking: 4,
    drape: 5,
    wrinkle: 1,
    durability: 4,
    occasions: ["Weekend", "Office", "Travel"],
    warmthAffinity: ["warm", "cool", "neutral"],
    sustainability: 4,
    skinFriendly: 5,
    eczemaFriendly: 5,
    dryFriendly: 5,
    thermalFit: { hotRunner: 4, coldRunner: 4 },
    care: "Easy machine wash, shape-keeping after many washes.",
    labelKeywords: ["Modal", "MicroModal"],
    why: "Twice as absorbent as cotton, drapes like a dream, almost never wrinkles.",
  },
  {
    slug: "ecovero-viscose",
    name: "EcoVero Viscose",
    alternativeNames: ["Viscose", "Rayon"],
    category: "regenerated",
    source: "Certified-sustainable wood pulp",
    texture: "Soft, fluid, slightly cool",
    tropicalFit: 4,
    breathability: 4,
    wicking: 3,
    drape: 5,
    wrinkle: 3,
    durability: 3,
    occasions: ["Going out", "Office", "Weekend"],
    warmthAffinity: ["warm", "cool", "neutral"],
    sustainability: 4,
    skinFriendly: 4,
    eczemaFriendly: 4,
    dryFriendly: 4,
    thermalFit: { hotRunner: 4, coldRunner: 3 },
    care: "Cold wash, hang dry. Conventional viscose can pill, so look for EcoVero or LENZING brands.",
    labelKeywords: ["EcoVero", "LENZING Viscose", "Sustainable viscose"],
    why: "The drape of silk at a fraction of the price. Picky about care.",
  },
  {
    slug: "bamboo-lyocell",
    name: "Bamboo Lyocell",
    category: "regenerated",
    source: "Bamboo pulp processed in closed-loop systems",
    texture: "Silky, very cool against skin",
    tropicalFit: 4,
    breathability: 4,
    wicking: 4,
    drape: 4,
    wrinkle: 2,
    durability: 3,
    occasions: ["Weekend", "Active", "Travel"] as Fabric["occasions"],
    warmthAffinity: ["warm", "cool", "neutral"],
    sustainability: 4,
    skinFriendly: 5,
    eczemaFriendly: 5,
    dryFriendly: 5,
    thermalFit: { hotRunner: 4, coldRunner: 4 },
    care: "Cold gentle wash. Look for closed-loop certification, conventional bamboo rayon is chemical-heavy.",
    labelKeywords: ["Bamboo Lyocell", "Closed-loop bamboo"],
    why: "Closed-loop processed bamboo. Avoid generic '100% bamboo' which is chemical viscose under a greenwashed name.",
  },

  // ─── NATURAL ANIMAL ───────────────────────────────────────────────────
  {
    slug: "silk",
    name: "Silk",
    category: "natural-animal",
    source: "Silkworm cocoons",
    texture: "Liquid drape, gleaming surface",
    tropicalFit: 4,
    breathability: 4,
    wicking: 3,
    drape: 5,
    wrinkle: 2,
    durability: 3,
    occasions: ["Going out", "Office"],
    warmthAffinity: ["warm", "cool", "neutral"],
    sustainability: 3,
    skinFriendly: 4,
    eczemaFriendly: 5,
    dryFriendly: 5,
    thermalFit: { hotRunner: 4, coldRunner: 4 },
    care: "Hand-wash cold or dry-clean. Sweat residue stains, treat promptly.",
    labelKeywords: ["100% Silk", "Mulberry Silk", "Habotai", "Charmeuse"],
    why: "Naturally thermoregulating (absorbs 30% of weight in moisture). Dermatologist-recommended for eczema thanks to its ultra-smooth surface.",
  },
  {
    slug: "wool",
    name: "Wool",
    category: "natural-animal",
    source: "Sheep fleece",
    texture: "Warm, dimensional, often slightly itchy",
    tropicalFit: 1,
    breathability: 3,
    wicking: 4,
    drape: 3,
    wrinkle: 1,
    durability: 5,
    occasions: ["Travel"],
    warmthAffinity: ["warm", "cool", "neutral"],
    sustainability: 4,
    skinFriendly: 3,
    eczemaFriendly: 1,
    dryFriendly: 2,
    thermalFit: { hotRunner: 1, coldRunner: 5 },
    care: "Hand-wash or dry-clean.",
    labelKeywords: ["100% Wool", "Merino Wool", "Lambswool"],
    why: "Best for air-con offices, highlands, or travel to cooler climates. Merino (17-22 micron) is the fine, less-itchy option but still skips for eczema.",
    redFlag: "Coarse wool is a classic eczema trigger. If you run cold but have sensitive skin, choose silk or fine merino over lambswool.",
  },

  {
    slug: "merino-wool",
    name: "Merino Wool",
    alternativeNames: ["Fine Merino"],
    category: "natural-animal",
    source: "Fine sheep wool (17-22 micron, non-medullated)",
    texture: "Fine, soft, not the itchy wool you remember",
    tropicalFit: 3,
    breathability: 4,
    wicking: 5,
    drape: 3,
    wrinkle: 1,
    durability: 4,
    occasions: ["Office", "Travel"],
    warmthAffinity: ["warm", "cool", "neutral"],
    sustainability: 4,
    skinFriendly: 4,
    eczemaFriendly: 2,
    dryFriendly: 3,
    thermalFit: { hotRunner: 3, coldRunner: 5 },
    care: "Often machine-washable cool; line dry. Hand-wash safest.",
    labelKeywords: ["100% Merino", "Merino Wool", "Fine Merino"],
    why: "The single best fabric for SEA office workers who freeze in air-con. Absorbs ~30% moisture without feeling damp; naturally odour-resistant for multi-day travel.",
  },

  // ─── SPECIALTY WEAVES (tropical-specific) ─────────────────────────────
  {
    slug: "seersucker",
    name: "Seersucker",
    category: "specialty",
    source: "Cotton (or blend) woven into puckered stripes",
    texture: "Puckered texture lifts fabric off skin, creating air gaps",
    tropicalFit: 5,
    breathability: 5,
    wicking: 4,
    drape: 3,
    wrinkle: 1,
    durability: 4,
    occasions: ["Office", "Weekend", "Going out"],
    warmthAffinity: ["warm", "cool", "neutral"],
    sustainability: 4,
    skinFriendly: 5,
    eczemaFriendly: 5,
    dryFriendly: 4,
    thermalFit: { hotRunner: 5, coldRunner: 2 },
    care: "Easy wash, no ironing required (the pucker IS the look).",
    labelKeywords: ["Seersucker", "Cotton seersucker"],
    why: "Built for tropics. The puckered weave keeps fabric off your skin, instant cool. Gentle on flare-prone skin (less surface contact).",
  },
  {
    slug: "dobby-cotton",
    name: "Dobby Cotton",
    category: "specialty",
    source: "Cotton woven with small geometric patterns and air pockets",
    texture: "Textured, slightly dimensional, very breathable",
    tropicalFit: 5,
    breathability: 5,
    wicking: 4,
    drape: 3,
    wrinkle: 3,
    durability: 4,
    occasions: ["Office", "Weekend"],
    warmthAffinity: ["warm", "cool", "neutral"],
    sustainability: 3,
    skinFriendly: 5,
    eczemaFriendly: 4,
    dryFriendly: 4,
    thermalFit: { hotRunner: 5, coldRunner: 2 },
    care: "Standard cotton care.",
    labelKeywords: ["Dobby weave", "Textured cotton"],
    why: "Small woven holes mean better airflow than regular cotton, lovely for office shirts.",
  },
  {
    slug: "eyelet-cotton",
    name: "Eyelet Cotton",
    alternativeNames: ["Broderie Anglaise"],
    category: "specialty",
    source: "Cotton with embroidered ventilation perforations",
    texture: "Decorative perforations let air through",
    tropicalFit: 5,
    breathability: 5,
    wicking: 3,
    drape: 3,
    wrinkle: 3,
    durability: 3,
    occasions: ["Weekend", "Going out"],
    warmthAffinity: ["warm", "cool", "neutral"],
    sustainability: 3,
    skinFriendly: 5,
    eczemaFriendly: 4,
    dryFriendly: 4,
    thermalFit: { hotRunner: 5, coldRunner: 2 },
    care: "Gentle wash to preserve embroidery.",
    labelKeywords: ["Eyelet", "Broderie anglaise"],
    why: "Romantic look with literal ventilation built in.",
  },

  // ─── BLENDS ──────────────────────────────────────────────────────────
  {
    slug: "linen-tencel",
    name: "Linen-Tencel Blend",
    category: "blend",
    source: "Linen + Lyocell mix",
    texture: "Crisp like linen but with silky drape and less wrinkle",
    tropicalFit: 5,
    breathability: 5,
    wicking: 5,
    drape: 4,
    wrinkle: 3,
    durability: 4,
    occasions: ["Office", "Going out", "Travel"],
    warmthAffinity: ["warm", "cool", "neutral"],
    sustainability: 4,
    skinFriendly: 5,
    eczemaFriendly: 5,
    dryFriendly: 4,
    thermalFit: { hotRunner: 5, coldRunner: 3 },
    care: "Gentle wash, hang dry. Best of both fibres.",
    labelKeywords: ["Linen-Tencel", "Linen-Lyocell blend"],
    why: "The fix for linen's main downside. Wrinkles less, drapes better, same wicking.",
  },
  {
    slug: "cotton-modal",
    name: "Cotton-Modal Blend",
    category: "blend",
    source: "Cotton + beech-pulp modal mix",
    texture: "Soft cotton hand with the fluid drape of modal",
    tropicalFit: 4,
    breathability: 4,
    wicking: 4,
    drape: 4,
    wrinkle: 2,
    durability: 4,
    occasions: ["Weekend", "Office", "Travel"],
    warmthAffinity: ["warm", "cool", "neutral"],
    sustainability: 3,
    skinFriendly: 5,
    eczemaFriendly: 5,
    dryFriendly: 5,
    thermalFit: { hotRunner: 4, coldRunner: 3 },
    care: "Standard wash, shape-keeping.",
    labelKeywords: ["Cotton-Modal", "Cotton/Modal"],
    why: "More comfortable than pure cotton for daily wear, especially tees and base layers.",
  },

  {
    slug: "cotton-linen",
    name: "Cotton-Linen Blend",
    alternativeNames: ["50/50 Linen-Cotton"],
    category: "blend",
    source: "Cotton + Linen mix (usually 50/50 or 70/30)",
    texture: "Linen coolness with cotton's softer hand, fewer sharp creases",
    tropicalFit: 5,
    breathability: 5,
    wicking: 5,
    drape: 3,
    wrinkle: 4,
    durability: 4,
    occasions: ["Office", "Weekend", "Going out", "Travel"],
    warmthAffinity: ["warm", "cool", "neutral"],
    sustainability: 4,
    skinFriendly: 5,
    eczemaFriendly: 4,
    dryFriendly: 4,
    thermalFit: { hotRunner: 5, coldRunner: 2 },
    care: "Machine wash cold, air-dry. Less ironing than pure linen.",
    labelKeywords: ["Cotton-Linen", "Linen-Cotton", "50/50 Linen Cotton"],
    why: "The sweet spot for SEA tropical shirts. Linen's coolness with cotton's structure and reduced creasing.",
  },

  // ─── SYNTHETICS (mostly avoid) ───────────────────────────────────────
  {
    slug: "polyester",
    name: "Polyester",
    category: "synthetic",
    source: "Petroleum-derived plastic fibre",
    texture: "Slippery to plasticky, traps heat against skin",
    tropicalFit: 1,
    breathability: 1,
    wicking: 1,
    drape: 3,
    wrinkle: 1,
    durability: 5,
    occasions: ["Travel"],
    warmthAffinity: ["warm", "cool", "neutral"],
    sustainability: 1,
    skinFriendly: 2,
    eczemaFriendly: 2,
    dryFriendly: 2,
    thermalFit: { hotRunner: 1, coldRunner: 3 },
    care: "Easy wash but builds up odours. Polyester fleece sheds ~7,360 microfibres per litre per wash (Carney Almroth et al. 2018).",
    labelKeywords: ["Polyester", "PET"],
    why: "Cheap, wrinkle-proof, but traps body heat. Skip for tropical wear. Performance polyesters (Dri-FIT) are a different story.",
    redFlag: "Polyester fleece is the worst microplastic shedder in your wardrobe. Heavy polyester anything traps sweat and bacteria.",
  },
  {
    slug: "performance-synthetic",
    name: "Performance Synthetic",
    alternativeNames: ["Dri-FIT", "Coolmax"],
    category: "synthetic",
    source: "Engineered polyester or nylon with wicking channels",
    texture: "Smooth, lightweight, designed to wick",
    tropicalFit: 4,
    breathability: 3,
    wicking: 5,
    drape: 2,
    wrinkle: 1,
    durability: 5,
    occasions: ["Outdoor", "Travel"],
    warmthAffinity: ["warm", "cool", "neutral"],
    sustainability: 2,
    skinFriendly: 3,
    eczemaFriendly: 2,
    dryFriendly: 1,
    thermalFit: { hotRunner: 3, coldRunner: 3 },
    care: "Cold wash, avoid fabric softener (clogs wicking).",
    labelKeywords: ["Dri-FIT", "Coolmax", "Wicking polyester", "Performance fabric"],
    why: "Right tool for sweaty workouts and humid outdoor commutes. Wrong tool for daily wear.",
  },
  {
    slug: "nylon",
    name: "Nylon",
    category: "synthetic",
    source: "Petroleum-derived polyamide",
    texture: "Smooth and stretchy",
    tropicalFit: 1,
    breathability: 1,
    wicking: 1,
    drape: 4,
    wrinkle: 1,
    durability: 5,
    occasions: ["Travel"],
    warmthAffinity: ["warm", "cool", "neutral"],
    sustainability: 1,
    skinFriendly: 3,
    eczemaFriendly: 2,
    dryFriendly: 2,
    thermalFit: { hotRunner: 1, coldRunner: 3 },
    care: "Standard wash.",
    labelKeywords: ["Nylon", "Polyamide"],
    why: "Use only in technical gear (swimwear, rain shells). Avoid in everyday wear.",
  },
  {
    slug: "acrylic",
    name: "Acrylic",
    category: "synthetic",
    source: "Petroleum-derived plastic, mimics wool",
    texture: "Fluffy but traps heat and sweat",
    tropicalFit: 1,
    breathability: 1,
    wicking: 1,
    drape: 3,
    wrinkle: 2,
    durability: 3,
    occasions: ["Travel"],
    warmthAffinity: ["warm", "cool", "neutral"],
    sustainability: 1,
    skinFriendly: 2,
    eczemaFriendly: 1,
    dryFriendly: 1,
    thermalFit: { hotRunner: 1, coldRunner: 3 },
    care: "Standard wash, pills easily within weeks (short-staple ~2-3 cN/tex).",
    labelKeywords: ["Acrylic"],
    why: "Worst fabric for tropics. Plastic that pretends to be wool. Skip entirely.",
    redFlag: "100% acrylic knitwear and high-acrylic wool blends (30/70) pill heavily within weeks. Friction from pills can trigger eczema flares.",
  },
];

/** Lookup helper. */
export function getFabric(slug: string): Fabric | undefined {
  return FABRICS.find((f) => f.slug === slug);
}
